apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: petclinic
  namespace: myapp       
spec:
  interval: 5m                 
  chart:
    spec:
      chart: ./app          
      sourceRef:
        kind: GitRepository
        name: petclinic-dev
        namespace: myapp
  values:
    namespace: myapp
    replicaCount: 1
    image:
      tag: "48"
    ingress:
      enabled: true
      host: "petclinic.local"
    hpa:
      minReplicas: 1