apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app
  namespace: flux-system        # HelmRelease CRD lives in flux-system
spec:
  interval: 5m                  # How often Flux checks for changes
  releaseName: petclinic          # Helm release name in cluster
  targetNamespace: myapp       # Namespace where app is deployed
  install:
    createNamespace: true       # Flux creates the namespace
  chart:
    spec:
      chart: ./app             # Path to your Helm chart (relative to repo root)
      sourceRef:
        kind: GitRepository
        name: flux-system      # Already bootstrapped Git repo
        namespace: flux-system
  values:
    replicaCount: 2             # Override default values
