apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: petclinic
  namespace: myapp
spec:
  interval: 5m     
  chart:
    path: ../../app
  values:
    image:
      tag: "48"
    hpa:
      minReplicas: 2
