apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: petclinic
  namespace: myapp       
spec:
  interval: 5m                 
  chart:
    spec:
      chart: ./app          
      sourceRef:
        kind: GitRepository
        name: my-app-repo
        namespace: myapp
  values:
    replicaCount: 2

