apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: petclinic-dev
  namespace: myapp
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/rizjosel/petclinic-config.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: petclinic-dev
  namespace: myapp
spec:
  interval: 10m0s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: petclinic-dev