apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-cluster/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
